### ISSUE TITLE
Dynamic Update Script

### ISSUE THREAD

**Issue by jzuellig** [loewexy/pdns-client#2]
@loewexy
Hi 

I'd like to provide a Dynamic DNS server to my friends.
But I don't want them to send Update to my server every five minutes.
My idea is to compare the current public ip address with the saved ip address on the server.

Do you thing you can create a function/feature whit a function like this?

I thought about something like this:
`#!/bin/sh

currentip=""	# WAN IP Adders at the moment
saveip=""	# Saved IP on DNS Server
success=""	# If update script was successful 
DATE=$(date "+%H:%M:%S   %d/%m/%y")
curl -s https://4.ifcfg.me/ > currentip	# Get public/WAN IP Adders
savedip=$(<savedip.txt)				# Get last save public/WAN IP Adders
mkdir -p /var/log/pdns/

if(currentip=!savedip); then
	echo -e "###########################################"  >> /var/log/pdns/update.log
	echo -e "# Last update at $DATE      #"
	echo -e "# New IP Adders is $currentip            "  >> /var/log/pdns/update.log
	./pdns-client -s https://dn5.ch/ -d <your RECORD>.dn5.ch -i 1 -c $currentip 
	success=$?
	if (success==0); then
		echo -e "# Update was successful               #"  >> /var/log/pdns/update.log
	else
		echo -e "# Update was not successful           #"  >> /var/log/pdns/update.log
	fi
	echo $currentip > savedip.txt	# Save public/WAN IP Adders of last update
else
	echo -e "###########################################"  >> /var/log/pdns/update.log
	echo -e "# No Update needed at $DATE #"> /var/log/pdns/update.log 
	echo -e "# Saved IP Adders is $savedip             #"  >> /var/log/pdns/update.log
fi
`

Regards
iGlaedr

**Comment by loewexy** [comment]
That is how a dynamic update can be done. But I do not consider this part of the client, it is a minimal implementation for the protocol. Think of it as libary for the Pdnsmanager protocol. You are welcome to make a project for this.

One hint: You don't have to use https://4.ifcfg.me/ but instead can use the API of Pdnsmanager to get the current IP.
